//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YourProjectWebApp.WebServiceYourProject {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Patron", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Patron : YourProjectWebApp.WebServiceYourProject.CRUDMethods {
        
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PatronNameField;
        
        private bool IsGroupField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PatronName {
            get {
                return this.PatronNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PatronNameField, value) != true)) {
                    this.PatronNameField = value;
                    this.RaisePropertyChanged("PatronName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool IsGroup {
            get {
                return this.IsGroupField;
            }
            set {
                if ((this.IsGroupField.Equals(value) != true)) {
                    this.IsGroupField = value;
                    this.RaisePropertyChanged("IsGroup");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CRUDMethods", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(YourProjectWebApp.WebServiceYourProject.Patron))]
    public partial class CRUDMethods : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebServiceYourProject.YourProjectServiceSoap")]
    public interface YourProjectServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllPatronsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPatrons", ReplyAction="*")]
        YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponse GetAllPatrons(YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPatrons", ReplyAction="*")]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponse> GetAllPatronsAsync(YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest request);
        
        // CODEGEN: Generating message contract since element name GetSinglePatronResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinglePatron", ReplyAction="*")]
        YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponse GetSinglePatron(YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSinglePatron", ReplyAction="*")]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponse> GetSinglePatronAsync(YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest request);
        
        // CODEGEN: Generating message contract since element name patron from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePatron", ReplyAction="*")]
        YourProjectWebApp.WebServiceYourProject.UpdatePatronResponse UpdatePatron(YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePatron", ReplyAction="*")]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.UpdatePatronResponse> UpdatePatronAsync(YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest request);
        
        // CODEGEN: Generating message contract since element name patron from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePatron", ReplyAction="*")]
        YourProjectWebApp.WebServiceYourProject.CreatePatronResponse CreatePatron(YourProjectWebApp.WebServiceYourProject.CreatePatronRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePatron", ReplyAction="*")]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.CreatePatronResponse> CreatePatronAsync(YourProjectWebApp.WebServiceYourProject.CreatePatronRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePatron", ReplyAction="*")]
        bool DeletePatron(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePatron", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeletePatronAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPatronsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPatrons", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequestBody Body;
        
        public GetAllPatronsRequest() {
        }
        
        public GetAllPatronsRequest(YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPatronsRequestBody {
        
        public GetAllPatronsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPatronsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPatronsResponse", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponseBody Body;
        
        public GetAllPatronsResponse() {
        }
        
        public GetAllPatronsResponse(YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPatronsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YourProjectWebApp.WebServiceYourProject.Patron[] GetAllPatronsResult;
        
        public GetAllPatronsResponseBody() {
        }
        
        public GetAllPatronsResponseBody(YourProjectWebApp.WebServiceYourProject.Patron[] GetAllPatronsResult) {
            this.GetAllPatronsResult = GetAllPatronsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinglePatronRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSinglePatron", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequestBody Body;
        
        public GetSinglePatronRequest() {
        }
        
        public GetSinglePatronRequest(YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSinglePatronRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetSinglePatronRequestBody() {
        }
        
        public GetSinglePatronRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSinglePatronResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSinglePatronResponse", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponseBody Body;
        
        public GetSinglePatronResponse() {
        }
        
        public GetSinglePatronResponse(YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSinglePatronResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YourProjectWebApp.WebServiceYourProject.Patron GetSinglePatronResult;
        
        public GetSinglePatronResponseBody() {
        }
        
        public GetSinglePatronResponseBody(YourProjectWebApp.WebServiceYourProject.Patron GetSinglePatronResult) {
            this.GetSinglePatronResult = GetSinglePatronResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePatronRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePatron", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.UpdatePatronRequestBody Body;
        
        public UpdatePatronRequest() {
        }
        
        public UpdatePatronRequest(YourProjectWebApp.WebServiceYourProject.UpdatePatronRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePatronRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YourProjectWebApp.WebServiceYourProject.Patron patron;
        
        public UpdatePatronRequestBody() {
        }
        
        public UpdatePatronRequestBody(YourProjectWebApp.WebServiceYourProject.Patron patron) {
            this.patron = patron;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePatronResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePatronResponse", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.UpdatePatronResponseBody Body;
        
        public UpdatePatronResponse() {
        }
        
        public UpdatePatronResponse(YourProjectWebApp.WebServiceYourProject.UpdatePatronResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePatronResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YourProjectWebApp.WebServiceYourProject.Patron UpdatePatronResult;
        
        public UpdatePatronResponseBody() {
        }
        
        public UpdatePatronResponseBody(YourProjectWebApp.WebServiceYourProject.Patron UpdatePatronResult) {
            this.UpdatePatronResult = UpdatePatronResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePatronRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePatron", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.CreatePatronRequestBody Body;
        
        public CreatePatronRequest() {
        }
        
        public CreatePatronRequest(YourProjectWebApp.WebServiceYourProject.CreatePatronRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePatronRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YourProjectWebApp.WebServiceYourProject.Patron patron;
        
        public CreatePatronRequestBody() {
        }
        
        public CreatePatronRequestBody(YourProjectWebApp.WebServiceYourProject.Patron patron) {
            this.patron = patron;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePatronResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePatronResponse", Namespace="http://tempuri.org/", Order=0)]
        public YourProjectWebApp.WebServiceYourProject.CreatePatronResponseBody Body;
        
        public CreatePatronResponse() {
        }
        
        public CreatePatronResponse(YourProjectWebApp.WebServiceYourProject.CreatePatronResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePatronResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public YourProjectWebApp.WebServiceYourProject.Patron CreatePatronResult;
        
        public CreatePatronResponseBody() {
        }
        
        public CreatePatronResponseBody(YourProjectWebApp.WebServiceYourProject.Patron CreatePatronResult) {
            this.CreatePatronResult = CreatePatronResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YourProjectServiceSoapChannel : YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YourProjectServiceSoapClient : System.ServiceModel.ClientBase<YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap>, YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap {
        
        public YourProjectServiceSoapClient() {
        }
        
        public YourProjectServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YourProjectServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YourProjectServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YourProjectServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponse YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.GetAllPatrons(YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest request) {
            return base.Channel.GetAllPatrons(request);
        }
        
        public YourProjectWebApp.WebServiceYourProject.Patron[] GetAllPatrons() {
            YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest inValue = new YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequestBody();
            YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponse retVal = ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).GetAllPatrons(inValue);
            return retVal.Body.GetAllPatronsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponse> YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.GetAllPatronsAsync(YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest request) {
            return base.Channel.GetAllPatronsAsync(request);
        }
        
        public System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.GetAllPatronsResponse> GetAllPatronsAsync() {
            YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest inValue = new YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.GetAllPatronsRequestBody();
            return ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).GetAllPatronsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponse YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.GetSinglePatron(YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest request) {
            return base.Channel.GetSinglePatron(request);
        }
        
        public YourProjectWebApp.WebServiceYourProject.Patron GetSinglePatron(int id) {
            YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest inValue = new YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequestBody();
            inValue.Body.id = id;
            YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponse retVal = ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).GetSinglePatron(inValue);
            return retVal.Body.GetSinglePatronResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponse> YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.GetSinglePatronAsync(YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest request) {
            return base.Channel.GetSinglePatronAsync(request);
        }
        
        public System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.GetSinglePatronResponse> GetSinglePatronAsync(int id) {
            YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest inValue = new YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.GetSinglePatronRequestBody();
            inValue.Body.id = id;
            return ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).GetSinglePatronAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YourProjectWebApp.WebServiceYourProject.UpdatePatronResponse YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.UpdatePatron(YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest request) {
            return base.Channel.UpdatePatron(request);
        }
        
        public YourProjectWebApp.WebServiceYourProject.Patron UpdatePatron(YourProjectWebApp.WebServiceYourProject.Patron patron) {
            YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest inValue = new YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.UpdatePatronRequestBody();
            inValue.Body.patron = patron;
            YourProjectWebApp.WebServiceYourProject.UpdatePatronResponse retVal = ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).UpdatePatron(inValue);
            return retVal.Body.UpdatePatronResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.UpdatePatronResponse> YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.UpdatePatronAsync(YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest request) {
            return base.Channel.UpdatePatronAsync(request);
        }
        
        public System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.UpdatePatronResponse> UpdatePatronAsync(YourProjectWebApp.WebServiceYourProject.Patron patron) {
            YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest inValue = new YourProjectWebApp.WebServiceYourProject.UpdatePatronRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.UpdatePatronRequestBody();
            inValue.Body.patron = patron;
            return ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).UpdatePatronAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        YourProjectWebApp.WebServiceYourProject.CreatePatronResponse YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.CreatePatron(YourProjectWebApp.WebServiceYourProject.CreatePatronRequest request) {
            return base.Channel.CreatePatron(request);
        }
        
        public YourProjectWebApp.WebServiceYourProject.Patron CreatePatron(YourProjectWebApp.WebServiceYourProject.Patron patron) {
            YourProjectWebApp.WebServiceYourProject.CreatePatronRequest inValue = new YourProjectWebApp.WebServiceYourProject.CreatePatronRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.CreatePatronRequestBody();
            inValue.Body.patron = patron;
            YourProjectWebApp.WebServiceYourProject.CreatePatronResponse retVal = ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).CreatePatron(inValue);
            return retVal.Body.CreatePatronResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.CreatePatronResponse> YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap.CreatePatronAsync(YourProjectWebApp.WebServiceYourProject.CreatePatronRequest request) {
            return base.Channel.CreatePatronAsync(request);
        }
        
        public System.Threading.Tasks.Task<YourProjectWebApp.WebServiceYourProject.CreatePatronResponse> CreatePatronAsync(YourProjectWebApp.WebServiceYourProject.Patron patron) {
            YourProjectWebApp.WebServiceYourProject.CreatePatronRequest inValue = new YourProjectWebApp.WebServiceYourProject.CreatePatronRequest();
            inValue.Body = new YourProjectWebApp.WebServiceYourProject.CreatePatronRequestBody();
            inValue.Body.patron = patron;
            return ((YourProjectWebApp.WebServiceYourProject.YourProjectServiceSoap)(this)).CreatePatronAsync(inValue);
        }
        
        public bool DeletePatron(int id) {
            return base.Channel.DeletePatron(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePatronAsync(int id) {
            return base.Channel.DeletePatronAsync(id);
        }
    }
}
